# Práctica 3: Ejercicio para entregar. 
## Vectores y Matrices: aritmética y normas.




## Pon aquí tu NOMBRE: Alberto Ramírez López


Los vectores y matrices de números complejos aparecen frecuentemente en Machine Learning. En concreto, en sistemas de reconocimiento del hablante (speech recognition) y más específicamente en la primera fase, donde se hace uso de una técnica de tratamiento de señales llamada **transformada discreta de Fourier**. En este ejercicio prácticaremos un poco con el tipo de vectores que aparecen en este campo.

Consideremos la llamada **matriz de la transformada discreta de Fourier** en dimensión 5:

$$
DFT = \left[\begin{array}{ccccc}
1 & 1 & 1 & 1\\
1 & e^{\frac{2\pi j}{5}} & e^{\frac{4\pi j}{5}} & e^{\frac{6\pi j}{5}} & e^{\frac{8\pi j}{5}}\\
1 & e^{\frac{4\pi j}{5}} & e^{\frac{8\pi j}{5}} & e^{\frac{12\pi j}{5}} & e^{\frac{16\pi j}{5}}\\
1 & e^{\frac{6\pi j}{5}} & e^{\frac{12\pi j}{5}} & e^{\frac{18\pi j}{5}} & e^{\frac{24\pi j}{5}}\\
1 & e^{\frac{8\pi j}{5}} & e^{\frac{16\pi j}{5}} & e^{\frac{24\pi j}{5}} & e^{\frac{32\pi j}{5}}
\end{array}
\right]
$$

Observa que las entradas de esta matriz tienen la forma $e^{\frac{2kn\pi j}{N}}$, con  $n=[0,1,2,3,4]$, $k = n^T$ y  $N=5$.

Introduce esta matriz siguiendo los siguiente pasos:

1) Introduce el escalar $N = 5$

2) Genera el vector $n = [0, 1, 2, 3, 4]$ usando el método **arange**

3) Genera el vector $k = n^T$ usando el método **reshape**

4) Genera la matriz $k*n$ (equivalente, en este caso, a k @ n)

5) Genera la matriz con entradas $\mbox{exp}\,((2j*\pi*k*n) / N)$



In [2]:
# Completar aquí (1 punto)
import numpy as np
from numpy.linalg import norm
import numpy.linalg as LA

N = 5
n = np.arange(N)
k = n.reshape((N, 1))
kn_matriz = k * n

DFT_matriz = np.exp((2j * np.pi * kn_matriz) / N)
DFT_matriz



# Fin Completar aquí ------------------------------------

array([[ 1.        +0.j        ,  1.        +0.j        ,
         1.        +0.j        ,  1.        +0.j        ,
         1.        +0.j        ],
       [ 1.        +0.j        ,  0.30901699+0.95105652j,
        -0.80901699+0.58778525j, -0.80901699-0.58778525j,
         0.30901699-0.95105652j],
       [ 1.        +0.j        , -0.80901699+0.58778525j,
         0.30901699-0.95105652j,  0.30901699+0.95105652j,
        -0.80901699-0.58778525j],
       [ 1.        +0.j        , -0.80901699-0.58778525j,
         0.30901699+0.95105652j,  0.30901699-0.95105652j,
        -0.80901699+0.58778525j],
       [ 1.        +0.j        ,  0.30901699-0.95105652j,
        -0.80901699-0.58778525j, -0.80901699+0.58778525j,
         0.30901699+0.95105652j]])

Utiliza la técnica de **slicing** estudiada en la práctica anterior para extraer la primer fila (que guardaremos en un vector denotado $v_1$) y la tercera columna de la matriz $DFT$ (guardada en $v_2$)


In [3]:
# Completar aquí (0.5 puntos)
DFT_reducida = DFT_matriz[1:, :][:, [0, 1, 3, 4]]

v1 = DFT_matriz[0, :]
v2 = DFT_matriz[:, 2]

DFT_reducida


# Fin Completar aquí ------------------------------------

array([[ 1.        +0.j        ,  0.30901699+0.95105652j,
        -0.80901699-0.58778525j,  0.30901699-0.95105652j],
       [ 1.        +0.j        , -0.80901699+0.58778525j,
         0.30901699+0.95105652j, -0.80901699-0.58778525j],
       [ 1.        +0.j        , -0.80901699-0.58778525j,
         0.30901699-0.95105652j, -0.80901699+0.58778525j],
       [ 1.        +0.j        ,  0.30901699-0.95105652j,
        -0.80901699+0.58778525j,  0.30901699+0.95105652j]])

 Calcula:

 1) $v_1 + v_2$

 2) $v_1*v_2$, componente a componente

 3) $v_1 / v_2$, componente a componente

 4) Si $u$ es el vector formado por la parte real de $v_1$ y $w$ es el vector formado por la parte real de $v_2$,  
 ¿son ortogonales los vectores $u$ y $w$?

In [4]:
# Completar aquí (1 punto)
Suma = v1 + v2
Producto = v1 * v2
Division = v1 / v2
u = v1.real
w = v2.real
Parte_real = np.dot(u, w)
Ortogonal = Parte_real == 0

Suma, Producto, Division, Ortogonal

# Fin Completar aquí ------------------------------------

(array([2.        +0.j        , 0.19098301+0.58778525j,
        1.30901699-0.95105652j, 1.30901699+0.95105652j,
        0.19098301-0.58778525j]),
 array([ 1.        +0.j        , -0.80901699+0.58778525j,
         0.30901699-0.95105652j,  0.30901699+0.95105652j,
        -0.80901699-0.58778525j]),
 array([ 1.        +0.j        , -0.80901699-0.58778525j,
         0.30901699+0.95105652j,  0.30901699-0.95105652j,
        -0.80901699+0.58778525j]),
 False)

Calcula las normas $2$, $1$ e $\infty$ de $w$

In [5]:
# Completar aquí (0.5 puntos)
from numpy.linalg import norm
import numpy.linalg as LA

Norma_1 = LA.norm(w, 1)
Norma_2 = LA.norm(w)
Norma_Inf = LA.norm(w, np.inf)
print(f"norma 1 de w = {Norma_1}")
print(f"norma 2 de w = {Norma_2}")
print(f"norma Infinito de w = {Norma_Inf}")

# Fin Completar aquí ------------------------------------

norma 1 de w = 3.2360679774997907
norma 2 de w = 1.5811388300841898
norma Infinito de w = 1.0


Introduce una matriz $A$ de 8 filas y 4 columnas con números enteros positivos aleatorios  
menores o iguales que 10 y calcula la matriz $S = A^{\top}A$.  
Imprime por pantalla las matrices $A$ y $S$.

In [6]:
# Completar aquí (0.5 puntos)
A = np.random.randint(1, 11, size=(8, 4))
S = A.T @ A

print("Matriz A:")
print(A)
print("\nMatriz S:")
print(S)



# Fin Completar aquí ------------------------------------

Matriz A:
[[ 8  9  5  5]
 [ 8  3  7 10]
 [ 6  9  5  5]
 [ 1  7  5  5]
 [ 1  2  3  4]
 [ 7 10  7  2]
 [ 6  7  1  1]
 [ 1  5  7  4]]

Matriz S:
[[252 276 196 183]
 [276 398 264 210]
 [196 264 232 200]
 [183 210 200 212]]


Introduce un vector $b$ no nulo de dimensión 4, el que quieras, y calcula el producto $Sb$  
(matriz por columna) y el productop $bS$ (fila por matriz) ¿Por qué sale el mismo resultado? 

In [7]:
# Completar aquí (1 punto)
b = np.array([1, 2, 3, 4])
S = A.T @ A
Sb = S @ b
bS = b @ S

print("Matriz Sb:\n", Sb)
print("Matriz bS:\n", bS)
print("Esta es la matriz S:\n", S)
#Sale el mismo resultado, porque S es una matriz simétrica y estas tienen la propiedad de que el orden de multiplicación no cambia el resultado.    

# Fin Completar aquí ------------------------------------

Matriz Sb:
 [2124 2704 2220 2051]
Matriz bS:
 [2124 2704 2220 2051]
Esta es la matriz S:
 [[252 276 196 183]
 [276 398 264 210]
 [196 264 232 200]
 [183 210 200 212]]


Calcula las partes triangular inferior y superior de $S$.

In [8]:
# Completar aquí (0.5 puntos)
Triangular_inf = np.tril(S)
Triangular_sup = np.triu(S)

print("Triangular inferior de S:")
print(Triangular_inf)

print("\nTriangular superior de S:")
print(Triangular_sup)


# Fin Completar aquí ------------------------------------

Triangular inferior de S:
[[252   0   0   0]
 [276 398   0   0]
 [196 264 232   0]
 [183 210 200 212]]

Triangular superior de S:
[[252 276 196 183]
 [  0 398 264 210]
 [  0   0 232 200]
 [  0   0   0 212]]


Si $d$ es la superdiagonal de $S$ (diagonal justo encima de la diagonal principal)  
construye una matriz diagonal cuya diagonal principal sea $d$. 

In [9]:
# Completar aquí (1 punto)

Super_diag = np.diag(S)
d = np.diag(Super_diag)

print(f"\nLa matriz diagonal cuya diagonal principal es d:\n {d}")

# Fin Completar aquí ------------------------------------


La matriz diagonal cuya diagonal principal es d:
 [[252   0   0   0]
 [  0 398   0   0]
 [  0   0 232   0]
 [  0   0   0 212]]


Calcula la inversa de S, su traza, su determinante, su rango
su norma de Frobenius y su número de condición.

In [10]:
# Completar aquí (1 punto)
S_inv = LA.inv(S)                                           #Inversa
print(f"inversa de S: \n {S_inv}")
print(f"traza de S = {np.trace(S)}")                        #Traza
print(f"determinante de S = {LA.det(S)}")                   #Determinante
print(f"rango de S = {LA.matrix_rank(S)}")                  #Rango

fro_S = LA.norm(S, "fro")                                   #Norma de Frobenius
print(f"norma de Frobenius de S = {fro_S}")
print(f"número de condición de S = {LA.cond(S, 'fro')}")    #Número de condición

# Fin Completar aquí ------------------------------------

inversa de S: 
 [[ 0.02358546 -0.01555322  0.01093774 -0.01527127]
 [-0.01555322  0.02139557 -0.02415438  0.01501908]
 [ 0.01093774 -0.02415438  0.05392255 -0.03638536]
 [-0.01527127  0.01501908 -0.03638536  0.03734768]]
traza de S = 1094
determinante de S = 34957136.000000015
rango de S = 4
norma de Frobenius de S = 961.472828529231
número de condición de S = 99.78881500474495


 Sean $u,v$ dos vectores no nulos vistos como matrices columna $n\times 1$. Observa que $1+v^{\top}u$ es un escalar, que suponemos no nulo. Prueba que la matriz $A = I+uv^{\top}$ es no singular y su inversa es
$$A^{-1}=I-\dfrac{uv^{\top}}{1+v^{\top}u}$$


In [11]:
# Completar aquí (2 puntos)


# EJERCICIO PARA HACER CON "LÁPIZ Y PAPEL" 


# Fin Completar aquí ------------------------------------


Comprueba con los vectores $u= [1, 2, -2, -1]$ y $v=[4, 5, -5, -4]$ de $\mathbb{R}^4$ que se cumple la identidad anterior

In [4]:
# Completar aquí (1 punto)
u = np.array([[1], [2], [-2], [-1]])
v = np.array([[4], [5], [-5], [-4]])

A_inv = np.identity(4) - ((u @ v.T)/(1 + v.T @ u))
Matriz_A = np.identity(4) + (u * v.T)

resultado = np.allclose(A_inv, LA.inv(Matriz_A))
print("La comprobación es:", resultado)

# Fin Completar aquí ------------------------------------

La comprobación es: True
