# Práctica 4: Ejercicio para entregar. 



## Pon aquí tu NOMBRE:  Alberto Ramírez López


## Matrices sparse

Introduce dos matrices aleatorias sparse $A$ y $B$. La matriz $A$ debe tener $10$ filas, $5$ columnas y  
una sparsity de $0.8$ y la matriz $B$ debe tener $5$ filas, $10$ columnas y una sparsity de $0.7$.


Imprímelas por pantalla


In [5]:
# Completar aquí (1,5 puntos)
from scipy import sparse

A = sparse.random(10, 5, density=0.2)
B = sparse.random(5, 10, density=0.3)  

print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}")


# Fin Completar aquí 

Matriz A:
  (6, 2)	0.9415671805769136
  (1, 1)	0.10551207817192809
  (9, 0)	0.0045652424381863455
  (3, 0)	0.24407006328518932
  (6, 1)	0.45244975660974607
  (9, 3)	0.5461633370328647
  (0, 3)	0.9262297582289822
  (0, 0)	0.08794466804730183
  (5, 4)	0.6053716683188151
  (8, 2)	0.3252825125988086
Matriz B:
  (1, 8)	0.5033104568658728
  (3, 4)	0.2203926047611401
  (1, 9)	0.12436340426814563
  (2, 4)	0.0023993697025370686
  (3, 6)	0.10013958656131905
  (1, 6)	0.6277046471402639
  (4, 5)	0.3791969776363352
  (2, 6)	0.6938836641339917
  (1, 2)	0.6634259771086599
  (4, 9)	0.3439803425470571
  (3, 0)	0.7534915667556635
  (2, 2)	0.3692987926321799
  (2, 1)	0.6993545432665624
  (3, 8)	0.6657693280980727
  (1, 5)	0.1250971620436101


Calcula $C=AB$ (producto matricial usual). Transforma la matriz $C$ de formato sparse a dense  
y llama $D$ a la nueva matriz. Calcula la sparsity de la matriz $D$.

In [6]:
# Completar aquí (1,5 puntos)
import numpy as np

C_sparse = A @ B
D = C_sparse.todense()
sparsity_D = 1.0 - np.count_nonzero(D) / D.size

print(f"Matriz C: \n{D}")
print(f"Sparsity de la matriz D: {sparsity_D}")
# Fin Completar aquí 

Matriz C: 
[[6.97906312e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.04134189e-01 0.00000000e+00 9.27522650e-02 0.00000000e+00
  6.16655364e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.99994536e-02 0.00000000e+00
  0.00000000e+00 1.31992615e-02 6.62304218e-02 0.00000000e+00
  5.31053323e-02 1.31218412e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.29555107e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.08235954e-01]
 [0.00000000e+00 6.58489286e-01 6.47886545e-01 

## Tensores

El fichero la_manga.jpg contiene dos fotos de La Manga del Mar Menor, una de los años 60 y otra actual. 

![imagen de La Manga del Mar Menor en los años 60 y en la actualidad](la_manga.jpg)

Carga dicho fichero y convierte la imagen en un tensor. A continuación,  
imprime por pantalla el tensor asociado a la imagen.

In [10]:
# Completar aquí (1 punto)
from PIL import Image

manga = Image.open('la_manga.jpg')
tensor_m = np.array(manga)

print(f"Tensor de la imagen:\n{tensor_m}")
# Fin Completar aquí 

Tensor de la imagen:
[[[192 192 192]
  [190 190 190]
  [189 189 189]
  ...
  [149 176 195]
  [149 176 195]
  [149 176 195]]

 [[193 193 193]
  [191 191 191]
  [189 189 189]
  ...
  [148 175 194]
  [148 175 194]
  [148 175 194]]

 [[194 194 194]
  [192 192 192]
  [190 190 190]
  ...
  [146 173 192]
  [146 173 192]
  [146 173 192]]

 ...

 [[184 184 184]
  [143 143 143]
  [121 121 121]
  ...
  [ 59  89  81]
  [ 61  91  83]
  [ 61  91  83]]

 [[174 174 174]
  [133 133 133]
  [119 119 119]
  ...
  [ 63  94  86]
  [ 65  96  88]
  [ 66  97  89]]

 [[160 160 160]
  [123 123 123]
  [117 117 117]
  ...
  [ 67  98  90]
  [ 70 101  93]
  [ 69 102  93]]]


Calcula la forma y dimensión del tensor generado. 

In [16]:
# Completar aquí (1 punto)
tensor_forma = tensor_m.shape
tensor_dim = tensor_m.ndim

print(f"Forma del tensor: {tensor_forma}")
print(f"Dimensión del tensor: {tensor_dim}")


# Fin Completar aquí 

Forma del tensor: (720, 960, 3)
Dimensión del tensor: 3


Utiliza la técnica de **slicing** que vimos en la práctica 3 para generar dos vectores de  
longitud 3. Uno de ellos, denotado **v1**, se ha de corresponder con la primera fila del  
tensor que ves por pantalla; el segundo vector, **v2**, está formado por la segunda fila  
que ves por pantalla.  

In [17]:
# Completar aquí (1,5 puntos)
v1 = tensor_m[0, 0, :]
v2 = tensor_m[0, 1, :]  

print(f"v1:\n{v1}")
print(f"v2:\n{v2}")
# Fin Completar aquí

v1:
[192 192 192]
v2:
[190 190 190]


Calcula:

1) el producto tensorial de **v1** y **v2**

2) el producto de Hadamard de **v1** y **v2**

3) el producto escalar de **v1** y **v2**

In [ ]:
# Completar aquí (1 punto)
#Producto tensorial
producto_tensorial = np.tensordot(v1, v2, axes=0)
#Producto de Hadamard
producto_hadamard = v1 * v2
#Producto escalar
producto_escalar = v1 @ v2

print(f"Producto tensorial de v1 y v2:\n{producto_tensorial}")
print(f"Producto de Hadamard de v1 y v2:\n{producto_hadamard}")
print(f"Producto escalar de v1 y v2: {producto_escalar}")
# Fin Completar aquí

Producto tensorial de v1 y v2:
[[128 128 128]
 [128 128 128]
 [128 128 128]]
Producto de Hadamard de v1 y v2:
[128 128 128]
Producto escalar de v1 y v2: 128


Introduce manualmente, usando **np.array()**, los vectores **v1** y **v2** anteriores  
y denótalos por **z1** y **z2**, respectivamente.

A continuación realiza los mismos cálculos (producto tensorial, producto de Hadamard y  
producto escalar) con los vectores **z1** y **z2**.

In [20]:
# Completar aquí (1 punto)
z1 = np.array([192, 192, 192])
z2 = np.array([190, 190, 190])
#Producto tensorial
producto_tensorial = np.tensordot(z1, z2, axes=0)
#Producto de Hadamard
producto_hadamard = z1 * z2
#Producto escalar
producto_escalar = z1 @ z2  

print(f"Producto tensorial de z1 y z2:\n{producto_tensorial}")
print(f"Producto de Hadamard de z1 y z2:\n{producto_hadamard}")
print(f"Producto escalar de z1 y z2: {producto_escalar}")
# Fin Completar aquí

Producto tensorial de z1 y z2:
[[36480 36480 36480]
 [36480 36480 36480]
 [36480 36480 36480]]
Producto de Hadamard de z1 y z2:
[36480 36480 36480]
Producto escalar de z1 y z2: 109440


Como puedes ver, obtienes resultados distintos. 

Busca una explicación para esta discrepancia de resultados mirando los atributos  
**shape**, **type** y **dtype** de los vectores **v1**, **v2**, **z1** y **z2**.


In [22]:
# Completar aquí (1,5 puntos)
print("Atributos de v1:")
print(f"shape: {v1.shape}, type: {type(v1)}, dtype: {v1.dtype}")

print("\nAtributos de v2:")
print(f"shape: {v2.shape}, type: {type(v2)}, dtype: {v2.dtype}")

print("\nAtributos de z1:")
print(f"shape: {z1.shape}, type: {type(z1)}, dtype: {z1.dtype}")

print("\nAtributos de z2:")
print(f"shape: {z2.shape}, type: {type(z2)}, dtype: {z2.dtype}")

#Se diferencian en que los vectores v1 y v2 tienen dtype: uint8, mientras que los z1 y z2 tienen dtype: int32
# Fin Completar aquí

Atributos de v1:
shape: (3,), type: <class 'numpy.ndarray'>, dtype: uint8

Atributos de v2:
shape: (3,), type: <class 'numpy.ndarray'>, dtype: uint8

Atributos de z1:
shape: (3,), type: <class 'numpy.ndarray'>, dtype: int32

Atributos de z2:
shape: (3,), type: <class 'numpy.ndarray'>, dtype: int32
