# Práctica 5: Ejercicio para entregar. 
  
  

## Pon aquí tu NOMBRE: Alberto Ramírez López

La matriz de Toeplitz de dimensión $n$ se define como:
$$
K_n = \left[
    \begin{array}{rrrrrrr}
    2 & -1 & 0 & 0 & 0 & \cdots & 0 \\ 
    -1 & 2 & -1 & 0 & 0 &\cdots & 0 \\
    0 & -1 & 2 & -1 & 0 &\cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
    0 & 0 & 0 & \cdots & -1 & 2 & -1\\
    0 & 0 & 0 & \cdots & 0 & -1 & 2\\
    \end{array}
    \right]
$$

Mirando la documentación de la función  
[scipy.linalg.toeplitz](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.toeplitz.html)  
define una función llamada toep que dado un número $n$ proporcione la matriz de Toeplitz $K_n$

In [2]:
# Completar aquí
import numpy as np
from scipy.linalg import toeplitz

def toep (n):
    columna_1 = np.zeros(n)
    columna_1[:2] = [2, -1]

    K_n = toeplitz(columna_1)
    return K_n

print(toep(5))
# Fin Completar aquí 

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


Para la matriz $K_5$ comprueba que es simétrica y no singular.  
Calcula su número de condición.

In [3]:
# Completar aquí
import numpy as np
from scipy.linalg import solve

K_5 = toep(5)
b = np.ones(5)

simetrica = solve(K_5, b, assume_a='sym')
print(simetrica)
num_cond = np.linalg.cond(K_5)
print("El número de condición es:", num_cond)

# Fin Completar aquí 

[2.5 4.  4.5 4.  2.5]
El número de condición es: 13.92820323027552


Calcula la factiorización $PLU$ de $K_5$ y comprueba el resultado haciendo uso de  
un operador booleano. 

In [4]:
# Completar aquí
from scipy.linalg import lu
import numpy as np

K_5 = toep(5)
P, L, U = lu(K_5)

#P es la matriz Permutación
#L es la matriz Triangular_inferior
#U es la matriz Triangular_superior sin la diagonal

resultado = np.allclose(P @ L @ U, K_5)
print("Comprobación del resultado de la factorización:", resultado)
# Fin Completar aquí 

Comprobación del resultado de la factorización: True


Calcula la factorización de Choleski de $K_5$ en la forma $K_5=LL^{\top}$ 

In [5]:
# Completar aquí
from scipy.linalg import cholesky

K_5 = toep(5)
L = cholesky(K_5, lower= True)

print(f"LL^t = \n  {L @ L.T}")
# Fin Completar aquí 

LL^t = 
  [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


Genera un fichero con extensión .py con nombre gs.py  
que contenga la función gauss_seidel de la práctica 5 y guárdalo en el directorio de trabajo

(si usas un notebook en Jupyter, puedes copiar la función en una celda y hacer  
Download as > Python(.py))

Importa la función mediante **from gs import gauss_seidel**.   
Sea $n$ el número dado por las dos últimas cifras de tu DNI  
(siempre que $n\geq 10$, en caso contrario invéntatelo) Genera un 1d-array (vector)  
de dimensión $n$ con todas sus componentes iguales a 1. Denótalo por $b$.


In [6]:
# Completar aquí
from gs import gauss_seidel
import numpy as np

n = 31
b = np.ones(n)
print("El vector b es:", b)
# Fin Completar aquí 

El vector b es: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1.]


Para el valor de $n$ que has tomado anteriormente, resuelve el sistema $K_n x = b$  
mediante el método de Gauss-Seidel.



In [12]:
# Completar aquí
from gs import gauss_seidel
import numpy as np

n = 31
K_n = toep(n)
b = np.ones(n)
x, iteraciones, error = gauss_seidel(K_n, b)

print(f"Solución es: \n{x}\n")
print(f"Iteraciones: {iteraciones}\n")
print(f"Error: {error}\n")
# Fin Completar aquí 

Solución es: 
[ 15.49999986  29.99999973  43.49999959  55.99999947  67.49999935
  77.99999923  87.49999913  95.99999903 103.49999895 109.99999888
 115.49999881 119.99999876 123.49999872 125.9999987  127.49999869
 127.99999869 127.4999987  125.99999872 123.49999876 119.99999881
 115.49999887 109.99999894 103.49999902  95.99999911  87.4999992
  77.9999993   67.49999941  55.99999953  43.49999964  29.99999976
  15.49999988]

Iteraciones: 1908

Error: 9.956879867327e-11

