# Práctica 6: Ejercicio para entregar. 
## Diagonalización y factorización SVD


# Pon tu NOMBRE aquí: Alberto Ramírez López

Determina si la matriz
$$A=\frac{1}{5}\left[\begin{array}{rrrrr}
-9&-2&8&2&-2\\
0&5&0&0&0\\
-8&-4&11&4&-4\\
2&6&-4&-1&6\\
-2&-6&4&6&-1
\end{array}\right]$$
es diagonalizable. En caso afirmativo, calcula una matriz invertible $P$  
tal que $A=PDP^{-1}$ con $D$ una matriz diagonal.

In [ ]:
# Completar aquí
import numpy as np
from numpy.linalg import eig, norm, inv, det

# Matriz A
A = (1 / 5) * np.array([
    [-9, -2, 8, 2, -2],
    [0, 5, 0, 0, 0],
    [-8, -4, 11, 4, -4],
    [2, 6, -4, -1, 6],
    [-2, -6, 4, 6, -1]
])

# Calculamos de autovalores y autovectores
autovalores, autovectores = eig(A)
# Verificamos si la matriz de autovectores es invertible, es decir, el rango es = al numero de autovectores linealmente independientes

if np.linalg.matrix_rank(autovectores) == A.shape[0]:
    print("La matriz es diagonalizable.")
    
    # Matriz de autovectores
    P = autovectores
    # Matriz diagonal de autovalores
    D = np.diag(autovalores)
    # Calculamos la inversa de P
    inv_P = inv(P)
    
    # Verificamos la diagonalización A = PDP^-1
    diagonalizacion = P @ D @ inv_P
    print("Verificación de la diagonalización A = PDP^-1:")
    print(diagonalizacion)
else:
    print("La matriz no es diagonalizable ya que no tiene suficientes autovectores linealmente independientes.")

# Fin Completar aquí 

La matriz es diagonalizable.
Verificación de la diagonalización A = PDP^-1:
[[-1.8 -0.4  1.6  0.4 -0.4]
 [ 0.   1.   0.   0.   0. ]
 [-1.6 -0.8  2.2  0.8 -0.8]
 [ 0.4  1.2 -0.8 -0.2  1.2]
 [-0.4 -1.2  0.8  1.2 -0.2]]


Introduce una matriz **B** de tamaño $12\times 7$ con entradas aleatorias



In [79]:
# Completar aquí

# Comando para formar la matriz B (12 x 7), de forma aleatoria
B = np.random.rand(12, 7)

# Matriz B
print("Matriz B:")
print(B)

# Fin Completar aquí 

Matriz B:
[[0.02164052 0.97896729 0.50807025 0.35660791 0.07906588 0.56840442
  0.05151747]
 [0.43658399 0.50090599 0.62413975 0.06579575 0.46803452 0.7988262
  0.45976354]
 [0.69740392 0.32793965 0.40296217 0.62367828 0.02734348 0.37336973
  0.45745635]
 [0.75379382 0.54188605 0.75461541 0.29737352 0.62439514 0.43689012
  0.78817248]
 [0.28402621 0.8136689  0.24549316 0.97432945 0.69590172 0.35926573
  0.46110436]
 [0.54176902 0.40888024 0.31984329 0.69518837 0.94508218 0.13922115
  0.53685124]
 [0.06920293 0.22962441 0.35986526 0.3370943  0.74832224 0.20480014
  0.50115499]
 [0.03067451 0.3597978  0.11074986 0.12089759 0.91118331 0.66169108
  0.66472707]
 [0.22819393 0.28851674 0.98585855 0.23997154 0.27529786 0.6012132
  0.90666448]
 [0.01797332 0.66225916 0.28178363 0.95678309 0.88372217 0.4537903
  0.63613254]
 [0.94168504 0.70023642 0.61735862 0.78469699 0.18526417 0.38662157
  0.51857659]
 [0.30904292 0.75469513 0.12294559 0.78839524 0.82733522 0.08444815
  0.38696597]]


Calcula la factorización **SVD** de la matriz $B$ anterior.
A partir de los valores singulares, construye la matriz $\Sigma$  
de la descomposición **SVD** y comprueba que $B=U\Sigma V^{\top}$


In [80]:
# Completar aquí
from scipy.linalg import svd

# Calculamos la descomposición de B
U, s, Vt = svd(B)   # s es un vector que contiene los valores singulares

# Matriz Sigma:
n = len(s)
Sigma = np.zeros_like(B, dtype=float)
Sigma[:n, :n] = np.diag(s)
print(f"Sigma = \n {Sigma}")

# Comprobamos que B = USV^T
print("Comprobación de B:", np.allclose(B, U @ Sigma @ Vt))

# Fin Completar aquí 

Sigma = 
 [[4.53270958 0.         0.         0.         0.         0.
  0.        ]
 [0.         1.46744929 0.         0.         0.         0.
  0.        ]
 [0.         0.         1.24488101 0.         0.         0.
  0.        ]
 [0.         0.         0.         1.00544961 0.         0.
  0.        ]
 [0.         0.         0.         0.         0.6048987  0.
  0.        ]
 [0.         0.         0.         0.         0.         0.4426208
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.20161665]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]
Comprobación de B: True


Utilizando los 4 primeros valores singulares, calcula una aproximación  
$B_4$ de rango 4 de $B$ y calcula el rango de $B$ y de $B_4$. Calcula también  
$||B-B_4||_2$

In [81]:
# Completar aquí

U,s,Vt = svd(B)
Long_s = len(s)

K = 4   # Número de valores singulares
Trunc_s=s[:K]  # Truncamos los valores singulares a los primeros K

# Creamos la matriz diagonal de los valores truncados    
Z = np.zeros_like(B, dtype=np.float64)
Z[:K, :K] = np.diag(Trunc_s)

# Aproximación de B usando los primeros K valores
B_aprox = U @ Z @ Vt

print("Rango de B:", np.linalg.matrix_rank(B))
print("Rango de B:", np.linalg.matrix_rank(B_aprox))
print ("Norma de B-B4:", np.linalg.norm(B-B_aprox))

# Fin Completar aquí 

Rango de B: 7
Rango de B: 4
Norma de B-B4: 0.7761861097094169
